apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-app
  name: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-app
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["sleep", "86400"]

  
