apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment-recreate
  name: nginx-deployment-recreate
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment-recreate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-deployment-recreate
    spec:
      containers:
      - image: nginx:1.19.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.25"
            memory: 128Mi

  
